### your site title here

title: Call Center Training Tips | Learn Skills to Pass Interviews
email: kevin@callcentertrainingtips.com
description: > # this means to ignore newlines until "baseurl:"
  Call Center Training Tips: Build confidence, improve skills, and pass call center interviews for high-paying BPO jobs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://callcentertrainingtips.com" # the base hostname & protocol for your site

permalink: /:title/

highlighter: rouge
markdown: kramdown
### exclude the instructions / write-up in the README.md


# Tracker
analytics: UA-30944342-1

# Comments
disqus-shortname: callcentertrainingtips


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  

sass:
 style: compressed

exclude:
- README.md

paginate: 40

url: "https://callcentertrainingtips.com" # the base hostname & protocol for your site

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

gems: [jekyll-seo-tag, jekyll-paginate, jekyll-feed, jekyll-redirect-from ]
