### your site title here

title: Call Center Training Tips
email: callcentertrainingtips@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Call Center Training Tips is a blog about personal development and skills required to get hired and to succeed in a call center.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://callcentertrainingtips.com" # the base hostname & protocol for your site

permalink: /:title/



highlighter: rouge
markdown: kramdown
### exclude the instructions / write-up in the README.md


# Tracker
analytics: UA-30944342-1

# Comments
disqus-shortname: callcentertrainingtips


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  

sass:
 style: compressed

exclude:
- README.md

paginate: 40

gems: [jekyll-seo-tag, jekyll-paginate]
