### your site title here

title: CALL CENTER TRAINING TIPS
email: callcentertrainingtips@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Call Center Training Tips. Want to get hired in a call center? Our simple call center lessons helps you to build confidence, learn skills and improve your English so you can pass call center interviews. Become the best version of yourself and begin qualifying for High Paying BPO jobs today.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://callcentertrainingtips.com" # the base hostname & protocol for your site

permalink: /:title/



highlighter: rouge
markdown: kramdown
### exclude the instructions / write-up in the README.md


# Tracker
analytics: UA-30944342-1

# Comments
disqus-shortname: callcentertrainingtips


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  

sass:
 style: compressed

exclude:
- README.md

paginate: 40

url: "https://callcentertrainingtips.com" # the base hostname & protocol for your site

plugins:
  - jekyll-sitemap

gems: [jekyll-seo-tag, jekyll-paginate ]
